### ISSUE TITLE
Add a link to the IRC channel on the website

### ISSUE THREAD

**Issue by andylolz** [codeforIATI/codeforiati.github.io#31]
### Is your feature request related to a problem? Please describe.

We currently link to https://webchat.freenode.net/#codeforiati in [this discuss post](https://discuss.iatistandard.org/t/code-for-iati-sharing-and-collaborating-on-iati-tools/1889/1), but not on codeforiati.org.

### Describe the solution you’d like

Add a link from codeforiati.org. Possibly we need a "contact" or "get in touch" or "get involved" page (my preference is for the last one!)

**Comment by andylolz** [comment]
If this sounds like a good plan, I’m happy to start work / send a PR.

**Comment by markbrough** [comment]
+1 sounds good!! I guess we could start by just taking the bullet-points from that Discuss post and putting them on their own page?

**Comment by andylolz** [comment]
This exists!
