### ISSUE TITLE
Datastore (& Validator) no longer mentioned on projects page?

### ISSUE THREAD

**Issue by siemvaessen** [codeforIATI/codeforiati.github.io#45]
Datastore no longer mentioned on the Projects page? Nor the Validator? I am sure a commit was mad for the Datastore last year, but it seems to be gone?

Perhaps I am overlooking things as I do not see any removal of [earlier 2020 commits ](https://github.com/codeforIATI/codeforiati.github.io/commit/3f3ffa106e50b139864e67cb6aeadb3f1e84f36c)for this.

**Comment by andylolz** [comment]
Eek – huge apologies @siemvaessen, this looks like my mistake. I removed it in #44 in error. I’ll re-add!

Re. the validator… I don’t _think_ it was ever listed here? I’ll check, though!

**Comment by andylolz** [comment]
I don’t _think_ the validator was ever listed here? I’ll check, though!

**Comment by andylolz** [comment]
Fixed in 4510d960d1cd00d09b9e9a5ee030c31419fc3a10. Apologies again!

**Comment by siemvaessen** [comment]
Thanks! And the validor was not mentioned.
