### ISSUE TITLE
List d-preview as a project on https://codeforiati.org

### ISSUE THREAD

**Issue by andylolz** [codeforIATI/codeforiati.github.io#50]
Tagging @stevieflow, @notshi and @xriss here!

Projects all come from here:
https://github.com/codeforIATI/codeforiati.github.io/tree/gh-pages/_projects

They’re ordered by filename I think, hence the slightly weird filenames! Either send a PR, or just add some text in this issue and I can add a new project for you.

WELCOME ABOARD!

**Comment by notshi** [comment]
Thank you @andylolz!

I'll send a PR for our other projects first and send in d-preview when that is set up proper.

**Comment by andylolz** [comment]
Fixed in #52!
