### ISSUE TITLE
List dQuery documentation

### ISSUE THREAD

**Issue by notshi** [codeforIATI/codeforiati.github.io#64]
Having spent some time on the [dQuery documentation](https://github.com/notshi/dquery), it feels concise enough to be shared with others.

Would it qualify as a C4I project? If so, will do a pull request here and the sidebar repo.

**Comment by andylolz** [comment]
Excellent – this looks incredibly useful! (I was aware that dQuery is super powerful, but I just don’t know how to use it!)

Yes, I think this certainly qualifies as a C4I project!

Do you want a codeforiati.org subdomain for it? Also, have you considered switching on github pages for the repo?

**Comment by notshi** [comment]
Thanks @andylolz! 

Hopefully this will make dQuery a bit easier to use - or at least show examples on how you can use it for specific queries.  
Do let me know if there's a specific thing you want queried and there aren't any examples how to. I'm learning as well :}

Also thanks for the offer! I'm going to leave it as it is for now as I find that it's easier to navigate within Github when I'm looking at the documentation. We're hoping to embed it on the dQuery page so you don't have to keep two tabs opened but that would be some time in the future. Hopefully then we might switch github pages?

**Comment by andylolz** [comment]
Fixed in #65.
