### ISSUE TITLE
Add Jekyll blog

### ISSUE THREAD

**Issue by matmaxgeds** [codeforIATI/codeforiati.github.io#9]
Probably best (easiest to manage, consistent UI etc) to make the whole site a Jekyll blog, and integrate the current homepage features back into that

Notes for Matt:
- https://github.com/BD-IATI/bd-iati.github.io and http://bd-iati.github.io/blog/
- http://jmcglone.com/guides/github-pages/
- https://github.com/barryclark/jekyll-now

**Comment by andylolz** [comment]
Leaving this open, because although we have jekyll now, the blog bit isn’t set up yet.

**Comment by andylolz** [comment]
Made a start at this in #23.

**Comment by andylolz** [comment]
I think #24 finished this one off!
